### ISSUE TITLE
Chapter 6 code?

### ISSUE THREAD

**Issue by mixmastamyk** [robertour/kivy-book-examples#2]
Hi, am enjoying the book.  Code for chapter 6 doesn't seem to be included.  Where can I find it?  Guess I'll start typing it in as I wait.

**Comment by robertour** [comment]
Sorry about the late reply. The code here is for the 1st edition of the book, I asked for permission to the editorial for it to be online (after I realized somebody else uploaded).

If you bought your book, you should be able to access the code of the 2nd edition from https://www.packtpub.com/.

**Comment by mixmastamyk** [comment]
Thanks, I finished the book months ago.
